### ISSUE TITLE
Publishing Nginx Proxy Manager (instead of a single service)

### ISSUE THREAD

**Issue by jboutros89** [fractalnetworksco/selfhosted-gateway#10]
Hello,

I was wondering whether there is a possibility to publish Nginx Proxy Manager (hosted locally) and let Nginx do the proxying for the multiple services (hosted inside).
I was able to publish Nginx and establish a tunnel with the VPS, however I am only able to access the Nginx proxy itself (not the other services hosted inside)

Thanks

**Comment by thebalaa** [comment]
It should work with the existing configuration with a setup like this:

npm.mydomain.com -> nginx proxy manager

app1.npm.mydomain.com -> app1
app2.npm.mydomain.com -> app2

Let me know if you run into any issues or have something else in mind.

**Comment by newverdun** [comment]
@jboutros89, @thebalaa  Could you provide the steps or examples to implement nginx proxy manager, I can't do it successfully

**Comment by thebalaa** [comment]
Hey @newverdun, there is now support for `FORWARD_ONLY` which is what you'd need to run NPM behind the selfhosted-gateway. See the example at the bottom of README.md. Let me know if you run into any issues.
