### ISSUE TITLE
Links must be recreated after gateway reboot

### ISSUE THREAD

**Issue by thebalaa** [fractalnetworksco/selfhosted-gateway#17]
Two fairly annoying issues with the current implementation:

1) Random port assignments from docker do not persist after reboot.
2) Gateway link container overwrites WireGuard keys in entrypoint

Possible solutions:

1) Generate random port number in create-link.sh and set it explicitly on the gateway's link container so it will persist on reboot
2) Add a check in gateway link's entrypoint for existing WireGuard private key, if it exists do not overwrite it

**Comment by natecovington** [comment]
I'm interested in helping fix this, without being able to reboot my cloud VPS it seems like this isn't production ready.  Seems like a coin toss between your possible solutions, how difficult is something like this to implement?

**Comment by rockinonthehubnotkansas** [comment]
Has there been any progress made on this issue?

**Comment by natecovington** [comment]
(FWIW, I started using BoringProxy instead)

**Comment by rfenouil** [comment]
I'd rather keep using selfhosted-gatewaybut this issue is annoying indeed...
Not using random ports would help ?
