### ISSUE TITLE
image not available

### ISSUE THREAD

**Issue by TylerBarnes** [fractalnetworksco/selfhosted-gateway#18]
The image seems to not be available anymore, was that intentional?

https://hub.docker.com/search?q=fractalnetworks%2Fgateway-client

```
Pulling link (fractalnetworks/gateway-client:latest)...
ERROR: pull access denied for fractalnetworks/gateway-client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by thebalaa** [comment]
the images were never published to DockerHub, you need to run `make docker` to build it locally

**Comment by TylerBarnes** [comment]
Ah, that makes sense, thank you!
