### ISSUE TITLE
Recommend DNS based certificate challenges for CERTS

### ISSUE THREAD

**Issue by latetedemelon** [fractalnetworksco/selfhosted-gateway#21]
Unless I'm mistaken this seems to require leaving port 80 open on the VPS which is not ideal.   Recommend updating to allow DNS based certificate challenges / generation.

**Comment by thebalaa** [comment]
correct, port 80 is typically left open in order to support http -> https redirecting which is the default behavior for Caddy. 

Definitely open to supporting DNS based cert challenges though and making which ports are left open configurable with a YAML file.
