### ISSUE TITLE
What does nginx:80 means?

### ISSUE THREAD

**Issue by thinhngo-x** [fractalnetworksco/selfhosted-gateway#25]
Hi,

I'm setting up this for my vaultwarden. My vaultwarden previously worked on localhost:7843. So in this case, should I expose nginx:7843 or should I keep nginx:80 as instructions?

Thanks

**Comment by thebalaa** [comment]
Expose should reference the internal port of the vaultwarden container

So if the vaultwarden container is listening on 80

It would be:

EXPOSE: vaultwarden:80

Note that the "vaultwarden" host name here corresponds to the vaultwarden service as defined in your docker-compose file. 

Let us know if you run into any issues.

**Comment by thinhngo-x** [comment]
Thanks. It has been resolved.
