### ISSUE TITLE
Links giving a blank screen

### ISSUE THREAD

**Issue by Ali-Hela** [fractalnetworksco/selfhosted-gateway#29]
I have set up everything and double-checked it. But after creating my first 3 links. They all resolved to a blank screen. So `https://tautulli.mydomain.tld/` gives me a blank page.

After testing with `tracert tautulli.mydomain.tld` I discovered that that packets eventually reach a datacenter of my VPS provider, Oracle. But there are no hops after that whatsoever.

Here's a screenshot of my rules in case it's useful
![image](https://github.com/fractalnetworksco/selfhosted-gateway/assets/52052529/41b09a01-cf93-48a9-b0e4-a980e200b9d1)

**Comment by thebalaa** [comment]
@Ali-Hela do you still need a hand troubleshooting this? Join us in #fractalnetworks:matrix.org on Matrix if you'd like to debug further

**Comment by Ali-Hela** [comment]
> @Ali-Hela do you still need a hand troubleshooting this? Join us in #fractalnetworks:matrix.org on Matrix if you'd like to debug further

Well I tried Tailscale and I'm happy with it. Thanks for the offer though, I'm closing this now.
