### ISSUE TITLE
DDNS for VPS. UDP gaming 

### ISSUE THREAD

**Issue by siliconhippy** [fractalnetworksco/selfhosted-gateway#3]
Excellent project !
Looks like I wouldn't need OpenVPN fee based projects like portmap anymore.

1. Can we use DDNS for the server VPS instead of a regular domain with fixed IP?
There are many domain registrars like Google and Cloudflare that support DDNS.

2. There is mention of raw UDP not tested.
But can we stream UDP Steam games (e.g., CSGO) in general ?

3. Nice to see Docker is not needed client side for servers behind NAT.
Any help with how to set up behind NAT devices without Docker? 
Windows 10 will bloat further with Docker Engine as opposed to a Linux OS.

**Comment by thebalaa** [comment]
> 1. Can we use DDNS for the server VPS instead of a regular domain with fixed IP?
> There are many domain registrars like Google and Cloudflare that support DDNS.

Sure, this should work as you expect. Just keep in mind you will need to configure your DDNS client appropriately. Ideally a wildcard record *.mydomain.com pointing to your non-static IP
 
> 2. There is mention of raw UDP not tested.
> But can we stream UDP Steam games (e.g., CSGO) in general ?

This should work, just expose the 18522 and 18523 on the link container that runs on the gateway,

> 3. Nice to see Docker is not needed client side for servers behind NAT.
> Any help with how to set up behind NAT devices without Docker?
> Windows 10 will bloat further with Docker Engine as opposed to a Linux OS.

Running the commands from `link-entrypoint.sh` should be all thats needed to get this working client side without Docker. Let me know if you run into any issues we can troubleshoot together.

**Comment by siliconhippy** [comment]
Thanks for the quick answers 😸
