### ISSUE TITLE
SSH Permission Denied During Client To Gateway Link

### ISSUE THREAD

**Issue by dermotk1337** [fractalnetworksco/selfhosted-gateway#33]
# Explanation: 

_Hi fractal team, while setting up your selfhosted-gateway I ran into a Permission Denied (publickey) error while creating the client to gateway link._

_I can access Client 》 Host & Host 》 Client via openssh CLI without issues & I have followed your guide to the letter as far as I am aware. More Details Below_

<details><summary>Details</summary>
<p>

**Local Operating system: Ubuntu Server 22.04 LTS
VPS Operating system: Ubuntu Server 22.04 LTS
VPS Host: Digital Ocean
Selfhosted-Gateway Version: Latest
Error : Permission denied (publickey)
Install State : Clean Install
SSH Key Algorithm: ed25519 w/ 200 derivation function rounds.
/root/.ssh directory permission : 777
/root/.ssh/ed25519 & ed25519.pub permission : 600
/gateway/selfhosted-gateway permission: 777 recursively (troubleshooting)
Error: Make *** [255] Permission Denied (PublicKey)
Installation User : root**

</p>
</details>

**_Kindest Regards 💯_**

**Comment by Dotsch2005** [comment]
I often run into the same problem.

The following helps me.

Check whether the SSH agent is running `eval "$(ssh-agent -s)"`

Check whether the key is also available `ssh-add -L`

If this is missing, it can be added with `ssh-add /root/.ssh/ed25519`

Please use the following commit for now: https://github.com/fractalnetworksco/selfhosted-gateway/commit/a82d9753b115e6e388162b73895c132316b8098e

**Comment by dermotk1337** [comment]
Solved! sorry for the late reply but your solution worked for me, is it possible to add these checks during the make process maybe?
