### ISSUE TITLE
error:0A000126:SSL routines::unexpected eof while reading

### ISSUE THREAD

**Issue by stutz64** [fractalnetworksco/selfhosted-gateway#35]
Hello,
I recently updated the selfhoted gateway server and received the following error, when trying to connect. I have tried several different subdomains (workout, music, auth, etc...) but receive from all instances the same error. I ran wget and then received:

`wget https://music.domain.xyz
`
Response:
--2024-02-18 19:26:10--  https://music.domain.xyz/
Resolving music.domain.xyz (music.domain.xyz)... 49.14.67.othernumber
Connecting to music.domain.xyz (music.domain.xyz)|49.14.67.othernumber|:443... connected.
OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.

**Comment by thebalaa** [comment]
Did you recreate each of your links? 

Unfortunately, this is required if you're coming from a version pre #31

**Comment by stutz64** [comment]
Hello @thebalaa, thank you for your response
Recreate? Should I delete the containers and redo the process of creating only the links? Do I need to repull the docker images?

**Comment by thebalaa** [comment]
Right. You will need to pull the latest from this repo run "make docker" then remove and recreate the links on both the client and gateway side. 

A reminder that we don't publish any containers to dockerhub so pulling them will fail.

**Comment by stutz64** [comment]
Thanks, will try it out at the weekend.
