### ISSUE TITLE
No mention of pub/pri key in README

### ISSUE THREAD

**Issue by jacobburrell** [fractalnetworksco/selfhosted-gateway#47]
Step #3 references Wireguard public/private key but nowhere in the README is it mentioned how/when to get these values.

```
GATEWAY_CLIENT_WG_PRIVKEY: 4M7Ap0euzTxq7gTA/WIYIt3nU+i2FvHUc9eYTFQ2CGI=
GATEWAY_LINK_WG_PUBKEY: Wipd6Pv7ttmII4/Oj82I5tmGZwuw6ucsE3G+hwsMR08=
```

**Comment by thebalaa** [comment]
These values are generated for you when creating links. You can find them in the output of the make link command or the .env file that is generated in your current working directory
