### ISSUE TITLE
Reusing certificates

### ISSUE THREAD

**Issue by samwh1te** [fractalnetworksco/selfhosted-gateway#48]
I found that for the gateway-client the certificates are stored in `/root/.local/share/caddy` but if I persist the directory it seems from the logs that the certificates are still being pulled from LetsEncrypt. I move my PC around frequently enough that I sometimes hit the 50 certificates per registered domain per week rate limit. Is there a way for me to get it to reuse the certificates on restart?
Loving this software!!

**Comment by thebalaa** [comment]
Upgrading to the most recent commits on main should resolve this. 

Unfortunately you will have to recreate all links on Gateway.

**Comment by samwh1te** [comment]
That's great to hear, thanks very much!!
