### ISSUE TITLE
Steps to run without docker on the client

### ISSUE THREAD

**Issue by Oujiii** [fractalnetworksco/selfhosted-gateway#7]
Hi!

I'm looking to run this on a client that doesn't have docker installed and I'm looking for the steps to achieve this. I looked into `link-entrypoint.sh` but I was unable to make it work properly, so I'd appreciate a more detailed guide on how to do it.

Thank you!

**Comment by Oujiii** [comment]
Hi! Thanks for replying!

I have not, since it mentions that Docker is optional for the client. My client already has the service I need exposed installed directly, so I'm trying to expose it without docker.  Is there a way moving forward for this or is Docker really required on the client as well?

**Comment by thebalaa** [comment]
Running the commands from: https://github.com/fractalnetworksco/selfhosted-gateway/blob/main/gateway/client-entrypoint.sh on the client and making sure your local service is listening on 8080 (http) and 8443(https) should work.

You can change the local ports by modifying the gateway's link container entrypoint then rebuilding the container with `make docker`

Let us know if you run into any issues.
