### ISSUE TITLE
Add support for Sofether VPN alongside of Wireshark

### ISSUE THREAD

**Issue by FliKites** [fractalnetworksco/selfhosted-gateway#8]
I would love to use SofetherVPN for the tunneling instead of Wireshark. 
What would I need to manually change to add a SofetherVPN endpoint instead of wireshark?

**Comment by thebalaa** [comment]
Hey @FliKites thanks for the note. What is it about SoftetherVPN that appeals to you over WireGuard?

**Comment by FliKites** [comment]
It can run over port 443, and the speeds using the SoftEtherVPN protocol are much faster in my experience. (Than openVPN and WireGuard) ---- On Mon, 26 Dec 2022 20:37:02 -0500  ***@***.***  wrote ----
Hey @FliKites thanks for the note. What is it about SoftetherVPN that appeals to you over WireGuard?

**Comment by thebalaa** [comment]
@FliKites SoftEtherVPN looks cool, thanks for sharing.

A good starting point would be to manually configure a SoftEtherVPN between a VPS and a local docker container. 

Give the gateway side of the tunnel an IP address of 10.0.0.1
Give the container side of the tunnel an IP address of 10.0.0.2 (doesn't really matter what the IPs are)

From there I would install nginx on the VPS (without Docker) then modify the `stream` section nginx.conf from this repo as such:

```
    stream {  
        map $ssl_preread_server_name $targetBackend {
           myapp.mydomain.com 10.0.0.2:443;
        } 
```

From there it would be a matter of moving the Gateway side of the tunnel configuration to happen on bootup  (in the link-entrypoint.sh) of the Gateway link container.

If you can get it working or close to working submit a PR and we'll merge it once we can verify it's working.

Thanks for the suggestion.

**Comment by FliKites** [comment]
Thanks for this. Will likely give it a whirl soon.  ---- On Wed, 11 Jan 2023 22:54:46 -0500  ***@***.***  wrote ----
@FliKites SoftEtherVPN looks cool, thanks for sharing.
A good starting point would be to manually configure a SoftEtherVPN between a VPS and a local docker container.
Give the gateway side of the tunnel an IP address of 10.0.0.1
Give the container side of the tunnel an IP address of 10.0.0.2 (doesn't really matter what the IPs are)
From there I would install nginx on the VPS (without Docker) then modify the stream section nginx.conf from this repo as such:
    stream {  
        map $ssl_preread_server_name $targetBackend {
           myapp.mydomain.com 10.0.0.2:443;
        } 

From there it would be a matter of moving the Gateway side of the tunnel configuration to happen on bootup  (in the link-entrypoint.sh) of the Gateway link container.
If you can get it working or close to working submit a PR and we'll merge it once we can verify it's working.
Thanks for the suggestion.

**Comment by thebalaa** [comment]
Looking forward to seeing it! Let me know if you need any additional help along the way.
