### ISSUE TITLE
Similar services

### ISSUE THREAD

**Issue by thgh** [fractalnetworksco/selfhosted-gateway#9]
How does this compare to LocalTunnel.me and Expose.dev?

Could be interesting to mention in readme.

**Comment by thebalaa** [comment]
At quick glance, those are services.

This project is standalone, there are no 3rd party providers beyond the
(VPS) infrastructure itself.

This project does not offer any introspection capabilities as all traffic
is encrypted between the client and the service, the gateway and
infrastructure provider are not privy to it.

In summary, with this project you must bring your own server and your own
domain.

**Comment by thgh** [comment]
Thanks, that's indeed true for Expose!

 [localtunnel](https://github.com/localtunnel/localtunnel) actually has an open source [server](https://github.com/localtunnel/server) component that is hostable using docker. It's different introspection wise though!
